"""
Credentials module for GitHub node.

Generated by agent-skills/credential-convert
Correlation ID: node-github-019
"""

from .base import BaseCredential
from .githubApi import GithubApiCredential

__all__ = [
    "BaseCredential",
    "GithubApiCredential",
]
