"""add is_webhook column to dynamic node table

Revision ID: 32efadf7f46f
Revises: 1e13479a1a0b
Create Date: 2025-08-07 04:58:33.697796+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32efadf7f46f'
down_revision: Union[str, None] = '1e13479a1a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dynamic_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_webhook', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dynamic_nodes', schema=None) as batch_op:
        batch_op.drop_column('is_webhook')

    # ### end Alembic commands ###
