"""Add is_schedule field to dynamic node

Revision ID: e5010e4fbfda
Revises: 59bf01a30e06
Create Date: 2025-08-30 08:35:49.356812+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5010e4fbfda'
down_revision: Union[str, None] = '59bf01a30e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dynamic_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_schedule', sa.Boolean(), nullable=True, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dynamic_nodes', schema=None) as batch_op:
        batch_op.drop_column('is_schedule')

    # ### end Alembic commands ###
