"""Add is_oauth2 field to CredentialType

Revision ID: 1e13479a1a0b
Revises: f888a559334f
Create Date: 2025-06-10 19:55:26.858099+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e13479a1a0b'
down_revision: Union[str, None] = 'f888a559334f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credential_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_oauth2', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credential_types', schema=None) as batch_op:
        batch_op.drop_column('is_oauth2')

    # ### end Alembic commands ###
