"""change webhook model

Revision ID: 7f8e10d7ad66
Revises: 0c926d65cd67
Create Date: 2025-08-18 08:52:28.854047+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f8e10d7ad66'
down_revision: Union[str, None] = '32efadf7f46f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook', schema=None) as batch_op:
        batch_op.alter_column('webhook_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_index('ix_webhook_webhook_id_method_path_length')
        batch_op.create_index('ix_webhook_webhook_id_method', ['webhook_id', 'method'], unique=False)
        batch_op.drop_column('path_length')
        batch_op.drop_column('webhook_path')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhook_path', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('path_length', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_index('ix_webhook_webhook_id_method')
        batch_op.create_index('ix_webhook_webhook_id_method_path_length', ['webhook_id', 'method', 'path_length'], unique=False)
        batch_op.alter_column('webhook_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
