#!/usr/bin/env python3
"""
Tests for UnknownNode implementation.

Generated by agent-skills/test-generate
Correlation ID: github-final-test-006
"""

import pytest
from unittest.mock import Mock, patch
from nodes.unknown import UnknownNode
from models import Node, WorkflowModel, NodeExecutionData


@pytest.fixture
def mock_workflow():
    """Create mock workflow."""
    return Mock(spec=WorkflowModel)


@pytest.fixture
def mock_node_data():
    """Create mock node data."""
    return Mock(spec=Node)


class TestUnknownNode:
    """Unit tests for UnknownNode."""
    
    def test_node_initialization(self, mock_workflow, mock_node_data):
        """Test that node initializes correctly."""
        node = UnknownNode(mock_node_data, mock_workflow)
        assert node is not None
        assert node.type == "Github"
    
    # No operations found in schema
    pass
    
    def test_execute_invalid_operation(self, mock_workflow, mock_node_data):
        """Test error handling for invalid operation."""
        node = UnknownNode(mock_node_data, mock_workflow)
        mock_node_data.parameters = {"resource": "unknown", "operation": "unknown"}
        
        with pytest.raises(ValueError, match="Unknown resource/operation"):
            node.execute([NodeExecutionData(json_data={"test": "data"})])
    
    def test_execute_with_continue_on_fail(self, mock_workflow, mock_node_data):
        """Test that errors are captured when continue_on_fail is True."""
        node = UnknownNode(mock_node_data, mock_workflow)
        mock_node_data.continue_on_fail = True
        mock_node_data.parameters = {"resource": "invalid", "operation": "invalid"}
        
        result = node.execute([NodeExecutionData(json_data={"test": "data"})])
        assert len(result) == 1
        assert len(result[0]) > 0
        assert "error" in result[0][0].json_data


# Integration tests (skipped by default)
@pytest.mark.integration
@pytest.mark.skip(reason="Requires live API credentials")
class TestUnknownNodeIntegration:
    """Integration tests for UnknownNode."""
    
    def test_live_api_call(self):
        """Test with live API (requires credentials)."""
        # TODO: Implement when credentials are available
        pass
