#!/usr/bin/env python3
"""
BaseNode Schema Validator

Validates node_schema.json files against the BaseNode contract.
This ensures all generated node schemas are compliant.

Usage:
    python scripts/validate_basenode_schema.py [path/to/node_schema.json]
    
If no path provided, validates all node_schema.json files in artifacts/.
"""

import sys
import json
from pathlib import Path

# Add parent to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from contracts import validate_basenode_schema, BaseNodeSchema


def validate_file(path: Path) -> tuple[bool, list[str]]:
    """
    Validate a single node_schema.json file.
    
    Returns: (valid, errors)
    """
    try:
        data = json.loads(path.read_text())
        result = validate_basenode_schema(data)
        return result.valid, result.errors
    except json.JSONDecodeError as e:
        return False, [f"Invalid JSON: {e}"]
    except Exception as e:
        return False, [f"Validation error: {e}"]


def find_schema_files(root: Path) -> list[Path]:
    """Find all node_schema.json files."""
    return list(root.glob("**/node_schema.json"))


def main() -> int:
    """Main validation function."""
    if len(sys.argv) > 1:
        # Validate specific file
        path = Path(sys.argv[1])
        if not path.exists():
            print(f"ERROR: File not found: {path}")
            return 1
        
        valid, errors = validate_file(path)
        if valid:
            print(f"✓ {path} - Valid BaseNode schema")
            return 0
        else:
            print(f"✗ {path} - Invalid")
            for error in errors:
                print(f"  - {error}")
            return 1
    
    # Find and validate all schema files
    repo_root = Path(__file__).parent.parent
    artifacts_dir = repo_root / "artifacts"
    
    if not artifacts_dir.exists():
        print("No artifacts directory found.")
        print("BaseNode schema validation is performed on generated node_schema.json files.")
        print()
        print("To validate a specific file:")
        print(f"  python {sys.argv[0]} path/to/node_schema.json")
        return 0
    
    schema_files = find_schema_files(artifacts_dir)
    
    if not schema_files:
        print("No node_schema.json files found in artifacts/")
        print("These are generated by the schema-build skill.")
        return 0
    
    print(f"Validating {len(schema_files)} BaseNode schema files...\n")
    
    valid_count = 0
    total_errors = 0
    
    for path in schema_files:
        relative = path.relative_to(repo_root)
        valid, errors = validate_file(path)
        
        if valid:
            print(f"[{relative}]")
            print(f"  ✓ Valid BaseNode schema")
            valid_count += 1
        else:
            print(f"[{relative}]")
            for error in errors:
                print(f"  ✗ {error}")
            total_errors += len(errors)
    
    print()
    print("=" * 50)
    print(f"Results: {valid_count}/{len(schema_files)} schemas valid")
    print(f"Total errors: {total_errors}")
    
    return 0 if valid_count == len(schema_files) else 1


def demo_validation():
    """Demonstrate validation with a sample schema."""
    sample = {
        "type": "n8n-nodes-base.telegram",
        "version": 1,
        "description": {
            "displayName": "Telegram",
            "name": "telegram",
            "description": "Send messages via Telegram",
            "group": ["output"],
            "version": 1,
            "inputs": ["main"],
            "outputs": ["main"],
            "credentials": [
                {"name": "telegramApi", "required": True}
            ],
        },
        "properties": {
            "parameters": [
                {
                    "name": "operation",
                    "displayName": "Operation",
                    "type": "options",
                    "default": "sendMessage",
                    "options": [
                        {"name": "Send Message", "value": "sendMessage"},
                        {"name": "Edit Message", "value": "editMessage"},
                    ],
                },
                {
                    "name": "chatId",
                    "displayName": "Chat ID",
                    "type": "string",
                    "required": True,
                    "description": "Unique identifier for the target chat",
                },
            ],
        },
    }
    
    print("Demo: Validating sample Telegram node schema...")
    result = validate_basenode_schema(sample)
    
    if result.valid:
        print("✓ Sample schema is valid")
        print(f"  Summary: {result.schema_summary}")
    else:
        print("✗ Sample schema is invalid")
        for error in result.errors:
            print(f"  - {error}")
    
    return result.valid


if __name__ == "__main__":
    if "--demo" in sys.argv:
        sys.exit(0 if demo_validation() else 1)
    sys.exit(main())
